workflows:
  android-workflow:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android:
        image: latest
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
    scripts:
      - name: Clean up old caches to prevent disk full
        script: |
          echo "Cleaning Gradle and Flutter caches..."
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.pub-cache/
          ./gradlew clean || true
          flutter clean || true

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - romerojerome82@gmail.com
