workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - romerojerome82@gmail.com
